---
cron_user: basil
cron_group: basil
app_name: unnamed

cron_root: /srv/cron
app_root: "{{ cron_root }}/{{ app_name }}"

virtualenv_root: "{{ cron_root }}/virtualenvs"
app_venv: "{{ virtualenv_root }}/{{ app_name }}"

app_envs: {}
app_script: "{{ app_root }}/{{ app_name }}.py"
log_path: "{{ cron_root }}/logs/{{app_name}}.log"

month: "*"
day: "*"
hour: 0,6,12,18
minute: 11

system_python_pkgs:
  - virtualenv

app_system_pkgs: []

app_python_deps:
  - {name: "git+https://github.com/eve-basil/common", editable: "no"}
