---
- name: Restart uwsgi app
  supervisorctl: name={{ app_service_name }} state=restarted config=/etc/supervisor/supervisord.conf
  become: yes

- name: Restart supervisord
  service: name=supervisor state=restarted
  become: yes

- name: Restart nginx
  service: name=nginx state=restarted
  become: yes
