---
- name: "** Prepare System Python"
  include: python.yml

- name: "** Prepare Nginx"
  include: nginx.yml

- name: "** Prepare Supervisor"
  include: supervisor.yml

- name: "** Prepare Web App Directories"
  include: directories.yml

- name: "** Prepare Uwsgi"
  include: uwsgi.yml

- name: "** Deploy App"
  include: app.yml
