---
- name: Install nginx webserver
  apt:
    pkg: nginx-full
    state: present
  become: yes
  tags:
    - apt
    - nginx

- name: Disable default configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes
  tags:
    - nginx
  notify: Restart nginx

- name: Set nginx directories permissions
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ web_group }}"
    mode: 0755
  with_items:
      - /var/log/nginx
      - /etc/nginx
      - /etc/nginx/sites-available
      - /etc/nginx/sites-enabled
  become: yes
  tags:
    - nginx

- name: Set nginx logs permissions
  file:
    path: "/var/log/nginx/{{ item }}"
    state: file
    owner: "{{ web_group }}"
    group: "{{ web_group }}"
    mode: 0644
  with_items:
      - access.log
      - error.log
  become: yes
  tags:
    - nginx

- name: Configure custom nginx log format
  lineinfile:
    insertbefore: access_log
    dest: "/etc/nginx/nginx.conf"
    line: "log_format custom '{{ nginx_access_log_format_combined }} {{ nginx_access_log_format_extras }}';"
  become: yes
  tags:
    - nginx
  notify: Restart nginx

- name: Configure status host
  template:
    src: nginx_status_conf.j2
    dest: "/etc/nginx/sites-available/nginx_status.conf"
  become: yes
  tags:
    - nginx
  when: nginx_status_host is defined
  notify: Restart nginx

# Configure app
- name: Configure virtual host
  template:
    src: nginx_app_conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_app_config }}"
  become: yes
  tags:
    - nginx
    - app-deploy
  notify: Restart nginx

- name: Link to enable nginx status configuration
  file:
    src: "/etc/nginx/sites-available/nginx_status.conf"
    path: "/etc/nginx/sites-enabled/nginx_status.conf"
    state: link
  become: yes
  tags:
    - nginx
  when: nginx_status_host is defined
  notify: Restart nginx

- name: Link to enable nginx app configuration
  file:
    src: "/etc/nginx/sites-available/{{ nginx_app_config }}"
    path: "/etc/nginx/sites-enabled/{{ nginx_app_config }}"
    state: link
  become: yes
  tags:
    - nginx
    - app-deploy
  notify: Restart nginx

