---
- name: Deploy wrapper script
  template:
    src: wrapper.sh.j2
    dest: "{{ app_root }}/start.sh"
    owner: "{{cron_user }}"
    group: "{{ cron_user }}"
    mode: 0744
  become: yes
  tags:
    - configure
    - configfile

- name: Install crontab entry for app
  cron:
    name: "{{ app_name }}"
    user: "{{ cron_user }}"
    month: "{{ month }}"
    day: "{{ day }}"
    hour: "{{ hour }}"
    minute: "{{ minute }}"
    job: "{{ app_root }}/start.sh >> {{ log_path }} 2>&1"
  become: yes
  become_user: "{{ cron_user }}"
  tags:
    - configure
    - crontab
